---

- name: "determine if version 2 or later"
  set_fact: elasticsearch_version_2=True
  when: "{{ elasticsearch_version | version_compare('2.0.0','>=') }}"

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, elasticsearch-install]

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'
  tags: [elasticsearch, elasticsearch-install]

- include: configure.yml
  tags: [elasticsearch, elasticsearch-configure]

- include: plugins.yml
  tags: [elasticsearch, elasticsearch-plugins]

- include: proxy.yml
  when: elasticsearch_proxy
  tags: [elasticsearch, elasticsearch-proxy]

- service: name=elasticsearch state=started enabled=yes
  tags: [elasticsearch]
